services:
  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: vidyadb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

#  backend:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    depends_on:
#      - postgres
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/taskdb
#      SPRING_DATASOURCE_USERNAME: admin
#      SPRING_DATASOURCE_PASSWORD: admin
#      CORS_ALLOWED_ORIGINS: http://localhost:4200
#    ports:
#      - "8080:8080"

#  frontend:
#    build:
#      context: ../task-frontend/task-manager
#      dockerfile: Dockerfile
#    depends_on:
#      - backend
#    ports:
#      - "4200:80"

volumes:
  postgres_data:
